# Generated by Django 3.2.11 on 2022-04-15 06:53

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionhistory',
            options={'verbose_name': 'TransactionHistory', 'verbose_name_plural': 'Transaction Histories'},
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='added_by',
            field=models.CharField(default=0, max_length=50, verbose_name=account.models.User),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
