# Generated by Django 3.2.11 on 2022-04-15 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220415_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='added_by',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='addedby_transactionhistory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_transactionhistory', to=settings.AUTH_USER_MODEL),
        ),
    ]
